MONGODB_URL = "MONGODB_URL"
MONGODB_PORT = "MONGODB_PORT"
NL2FLOW_MONGODB_DATABASE = "nl2flowdb"

NL2FLOW_MONGODB_COLLECTION = "nl2flow"

NL2FLOW_LLM_MONGODB_COLLECTION = "llm_nl2flow"
NL2FLOW_CONCISE_LLM_MONGODB_COLLECTION = "llm_concise_nl2flow"
NL2FLOW_JSON_LLM_MONGODB_COLLECTION = "llm_json_nl2flow"

NL2FLOW_VALIDATION_MONGODB_COLLECTION = "validation_nl2flow"
NL2FLOW_CONCISE_VALIDATION_MONGODB_COLLECTION = "validation_concise_nl2flow"
NL2FLOW_JSON_VALIDATION_MONGODB_COLLECTION = "validation_json_nl2flow"

NL2FLOW_MONGODB_FAILED_COLLECTION = "nl2flowfailed"

DESCRIPTION_PLAN_MONGODB_COLLECTION = "dscp2plan"
DESCRIPTION_PLAN_MONGODB_FAILED_COLLECTION = "dscp2planfailed"
DESCRIPTION_PDDL_MONGODB_COLLECTION = "dscp2pddl"
DESCRIPTION_PDDL_MONGODB_FAILED_COLLECTION = "dscp2pddlfailed"
PDDL_PLAN_MONGODB_COLLECTION = "pddl2plan"
PDDL_PLAN_MONGODB_FAILED_COLLECTION = "pddl2planfailed"
PDDL_SYM_PLAN_MONGODB_COLLECTION = "pddlsymplan"
PDDL_SYM_PLAN_MONGODB_FAILED_COLLECTION = "pddlsymplanfailed"

MONGODB_USERNAME = "MONGODB_USERNAME"
MONGODB_PASSWORD = "MONGODB_PASSWORD"
MONGODB_USERNAME_DEFAULT = "admin"
MONGODB_PASSWORD_DEFAULT = "admin"

DB_TASK_DELETE = "delete"
DB_TASK_RETRIEVE = "retrieve"
